---
title: "Denver rental cost"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: "Nat Price"
date: "May 25, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggrepel)
library(ggmap)
library(osmdata)
library(sf)
library(leaflet)
library(viridis)

theme_set(theme_bw())
```

## Median Rent (single family residential)
Temporal trends in median rental price of single family residential (SFR) homes
for select cities in Denver metro area.

```{r medRentSFR}
rentalCity <- read_csv("City_MedianRentalPrice_Sfr.csv") %>% 
  select(RegionName, State, Metro, CountyName, SizeRank, 
         starts_with("2016"),
         starts_with("2017"),
         starts_with("2018")) %>% 
  filter(State == "CO",
         RegionName %in% c("Denver",
                           "Lakewood",
                           "Englewood",
                           "Edgewater",
                           "Golden",
                           "Wheat Ridge",
                           "Westminster",
                           "West Pleasant View")) %>% 
  gather(date, rent, `2016-01`:`2018-12`)

ggplot(data = rentalCity %>% 
         mutate(label = if_else(date == "2018-12", RegionName, NA_character_)),
       aes(x = date, y = rent, color = RegionName, group = RegionName)) +
  geom_line() +
  scale_x_discrete(expand = expand_scale(mult = c(0, 0.25))) +
  geom_label_repel(aes(label = label),
                  nudge_x = 1,
                  na.rm = TRUE) +
  scale_color_brewer(palette = "Dark2") +
  labs(x = "date", y = "median rent (SFR)") +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1))
```

Chloropleth map of median rental price of SFR homes in April of 2019.

```{r mapMedRentSFR, fig.width = 8, fig.height = 8, fig.align = "center"}
placeRent <- read_csv("City_MedianRentalPrice_Sfr.csv") %>% 
  select(RegionName, State, Metro, CountyName, SizeRank, rent = `2019-04`) %>% 
  filter(State == "CO")

# Load shapefile
coloradoPlaces <- st_read("tl_2018_08_place") %>%
  st_crop(xmin = -105.5, xmax = -103.5, ymin = 39, ymax = 40.5) %>% 
  left_join(placeRent, by = c("NAME" = "RegionName"))

# Color palette
pal <- colorNumeric("YlOrRd", domain = coloradoPlaces$rent)
# pal <- colorQuantile("YlOrRd", domain = coloradoPlaces$ZRI, probs = seq(0, 1, by = 0.1))

labels <- sprintf(
  "<strong>%s</strong><br/>Median rent (SFR): %g",
  coloradoPlaces$NAME, coloradoPlaces$rent
) %>% lapply(htmltools::HTML)

# Create leaflet chloropleth
leaflet(coloradoPlaces) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~ pal(rent),
    weight = 1,
    opacity = 1,
    color = "black",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 2,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto")
  ) %>% 
  addLegend(
    pal = pal, 
    values = ~ rent,
    opacity = 0.7, 
    title = "Median Rent (SFR)",
    position = "bottomright")
```

## Median Rent per Square Foot (single family residential)

```{r medRentSqFtSFRNational}
rentalCity <- read_csv("City_MedianRentalPricePerSqft_Sfr.csv") %>% 
  select(RegionName, State, Metro, CountyName, SizeRank, 
         starts_with("2016"),
         starts_with("2017"),
         starts_with("2018")) %>% 
  filter(State %in% c("CO", "NE", "FL"),
         RegionName %in% c("Denver",
                           "Lakewood",
                           "Lincoln",
                           "Gainesville")) %>% 
  gather(date, rent, `2016-01`:`2018-12`)

ggplot(data = rentalCity %>% 
         mutate(label = if_else(date == "2018-12", RegionName, NA_character_)),
       aes(x = date, y = rent, color = RegionName, group = RegionName)) +
  geom_line() +
  scale_x_discrete(expand = expand_scale(mult = c(0, 0.25))) +
  geom_label_repel(aes(label = label),
                  nudge_x = 1,
                  na.rm = TRUE) +
  scale_color_brewer(palette = "Dark2") +
  labs(x = "date", y = "median rent / sq. ft. (SFR)") +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r medRentSqFtSFR}
rentalCity <- read_csv("City_MedianRentalPricePerSqft_Sfr.csv") %>% 
  select(RegionName, State, Metro, CountyName, SizeRank, 
         starts_with("2016"),
         starts_with("2017"),
         starts_with("2018")) %>% 
  filter(State == "CO",
         RegionName %in% c("Denver",
                           "Lakewood",
                           "Englewood",
                           "Edgewater",
                           "Golden",
                           "Wheat Ridge",
                           "Westminster",
                           "West Pleasant View")) %>% 
  gather(date, rent, `2016-01`:`2018-12`)

ggplot(data = rentalCity %>% 
         mutate(label = if_else(date == "2018-12", RegionName, NA_character_)),
       aes(x = date, y = rent, color = RegionName, group = RegionName)) +
  geom_line() +
  scale_x_discrete(expand = expand_scale(mult = c(0, 0.25))) +
  geom_label_repel(aes(label = label),
                  nudge_x = 1,
                  na.rm = TRUE) +
  scale_color_brewer(palette = "Dark2") +
  labs(x = "date", y = "median rent / sq. ft. (SFR)") +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r mapMedRentSqFtSFR, fig.width = 8, fig.height = 8, fig.align = "center"}
placeRent <- read_csv("City_MedianRentalPricePerSqft_Sfr.csv") %>% 
  select(RegionName, State, Metro, CountyName, SizeRank, rent = `2019-04`) %>% 
  filter(State == "CO")

# Load shapefile
coloradoPlaces <- st_read("tl_2018_08_place") %>%
  st_crop(xmin = -105.5, xmax = -103.5, ymin = 39, ymax = 40.5) %>% 
  left_join(placeRent, by = c("NAME" = "RegionName"))

# Color palette
pal <- colorNumeric("YlOrRd", domain = coloradoPlaces$rent)
# pal <- colorQuantile("YlOrRd", domain = coloradoPlaces$ZRI, probs = seq(0, 1, by = 0.1))

labels <- sprintf(
  "<strong>%s</strong><br/>Median rent / sq. ft. (SFR): %g",
  coloradoPlaces$NAME, coloradoPlaces$rent
) %>% lapply(htmltools::HTML)

# Create leaflet chloropleth
leaflet(coloradoPlaces) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~ pal(rent),
    weight = 1,
    opacity = 1,
    color = "black",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 2,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto")
  ) %>% 
  addLegend(
    pal = pal, 
    values = ~ rent,
    opacity = 0.7, 
    title = "Median Rent / sq. ft.(SFR)",
    position = "bottomright")
```

## Zillow Rent Index (single family residential)

```{r zriSFR}
rentalCity <- read_csv("City_Zri_SingleFamilyResidenceRental.csv") %>% 
  select(RegionName, State, Metro, CountyName, SizeRank, 
         starts_with("2016"),
         starts_with("2017"),
         starts_with("2018")) %>% 
  filter(State == "CO",
         RegionName %in% c("Denver",
                           "Lakewood",
                           "Englewood",
                           "Edgewater",
                           "Golden",
                           "Wheat Ridge",
                           "Westminster",
                           "West Pleasant View")) %>% 
  gather(date, rent, `2016-01`:`2018-12`)

ggplot(data = rentalCity %>% 
         mutate(label = if_else(date == "2018-12", RegionName, NA_character_)),
       aes(x = date, y = rent, color = RegionName, group = RegionName)) +
  geom_line() +
  scale_x_discrete(expand = expand_scale(mult = c(0, 0.25))) +
  geom_label_repel(aes(label = label),
                  nudge_x = 1,
                  na.rm = TRUE) +
  scale_color_brewer(palette = "Dark2") +
  labs(x = "date", y = "Zillow rent index (SFR)") +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r mapZriSFR, fig.width = 8, fig.height = 8, fig.align = "center"}
placeRent <- read_csv("City_Zri_SingleFamilyResidenceRental.csv") %>% 
  select(RegionName, State, Metro, CountyName, SizeRank, rent = `2019-04`) %>% 
  filter(State == "CO")

# Load shapefile
coloradoPlaces <- st_read("tl_2018_08_place") %>%
  st_crop(xmin = -105.5, xmax = -103.5, ymin = 39, ymax = 40.5) %>% 
  left_join(placeRent, by = c("NAME" = "RegionName"))

# Color palette
pal <- colorNumeric("YlOrRd", domain = coloradoPlaces$rent)
# pal <- colorQuantile("YlOrRd", domain = coloradoPlaces$ZRI, probs = seq(0, 1, by = 0.1))

labels <- sprintf(
  "<strong>%s</strong><br/>Zillow rent index (SFR): %g",
  coloradoPlaces$NAME, coloradoPlaces$rent
) %>% lapply(htmltools::HTML)

# Create leaflet chloropleth
leaflet(coloradoPlaces) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~ pal(rent),
    weight = 1,
    opacity = 1,
    color = "black",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 2,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE),
    label = labels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto")
  ) %>% 
  addLegend(
    pal = pal, 
    values = ~ rent,
    opacity = 0.7, 
    title = "Zillow Rent Index (SFR)",
    position = "bottomright")
```

